language: go
sudo: false

os:
  - linux
  - osx

go:
  - 1.7
  - 1.8

script:
  - go vet ./...
  - go build -v ./...
  - go install -v
  - go test -v ./ansi
  - go test -v ./decorate
  - go test -v ./decorate/basic
  - go test -v ./decorate/curly
  - go test -v ./generic
