language: go
sudo: false

os:
  - linux
  - osx

go:
  - 1.7
  - 1.8
  - tip

install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - go vet ./...
  - go build -v ./...
  - go install -v
  - go test -v -covermode=count -coverprofile=coverage.out ./ansi
  - go test -v -covermode=count -coverprofile=coverage.out ./decorate
  - go test -v -covermode=count -coverprofile=coverage.out ./decorate/basic
  - go test -v -covermode=count -coverprofile=coverage.out ./decorate/curly
  - go test -v -covermode=count -coverprofile=coverage.out ./generic
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci

after_success:
  - coveralls
